<?php
  $title = 'Login';
  $this->headTitle($this->escapeHtml($title));
?>
<?php if (isset($_SESSION['user']->loggedin)): ?>
<h1>Welcome <?php echo $_SESSION['user']->username; ?>, you are logged in.</h1>
<h2>You will now be redirected to the homepage.</h2>
<?php $this->headMeta()->appendHttpEquiv('Refresh', '2;URL='.$this->serverUrl().'/'); ?>
<?php else: ?>
<div id="login-form-wrapper">
  <h1><?php echo $this->escapeHtml($title); ?>:</h1>
  <?php
  $form->setAttribute('action', $this->url('login', array('action' => 'add')));
  $form->prepare();
    echo $this->form()->openTag($form);
    echo $this->formRow($form->get('username'));
    echo $this->formRow($form->get('password'));
    echo $this->formSubmit($form->get('submit'));
    echo $this->form()->closeTag();
  ?>
</div>
<?php endif ?>
