<div class="test-sidebar-wrapper clearfix">
  <h3>Test Sidebar:</h3>
  <ul>
    <li><a href="#">one</a></li>
    <li><a href="#">two</a></li>
    <li><a href="#">three</a></li>
    <li><a href="#">four</a></li>
  </ul>

  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent sodales libero vitae lacus mattis fringilla. Vestibulum consequat ante quis dui ultricies elementum. Nam sed augue placerat, condimentum felis vel, elementum lacus. Nulla eleifend nibh dui, id iaculis elit faucibus eu. Aenean volutpat, sem sed lacinia placerat, erat sapien aliquam urna, eget suscipit nibh mauris sed tellus.</p>
  <p>Etiam aliquet arcu in gravida imperdiet. Fusce ac maximus ligula. Aliquam erat volutpat. Curabitur id sem venenatis, sollicitudin nunc commodo, dignissim turpis. Quisque eleifend ante eget elit convallis fermentum. Integer quam nisi, dictum vel elit ac, gravida sagittis magna. Morbi et erat id turpis aliquam maximus.</p>
</div>
