<?php
$title = 'Edit blog';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<div id="blog-form-wrapper">
  <?php
  $form = $this->form;
  $form->setAttribute('action', $this->url(
      'blog/edit',
      array(
          'action' => 'edit',
          'slug'     => $this->slug,
      )
  ));
  $form->prepare();

  echo $this->form()->openTag($form);
  echo $this->formHidden($form->get('id'));
  echo $this->formHidden($form->get('page_url'));

  echo $this->formRow($form->get('post_title'));
  echo $this->formRow($form->get('page_url'));
  echo $this->formRow($form->get('tags'));
  echo $this->formRow($form->get('post_body'));
  echo $this->formRow($form->get('active'));
  echo $this->formSubmit($form->get('submit'));
  echo $this->form()->closeTag();
  ?>
</div>
