<?php
  $this->headTitle('Blog');
  $this->headMeta()->appendName('keywords', '');
  $this->headMeta()->appendName('description', '');
?>
<?php foreach ($this->paginator as $post): ?>
<div class="blog-post">
  <h3><a href="<?php echo $this->url('blog/post', array('slug' => $post->page_url)); ?>"><?php echo $post->post_title; ?></a></h3>
  <h4><?php echo gmdate('n/j/Y - g:ia', $post->unix_time); ?></h4>
  <div class="blog-post-body">
    <?php echo $post->post_body; ?>
    <p class="read-more"><a href="<?php echo $this->url('blog/post', array('slug' => $post->page_url)); ?>">Read More &gt;</a></p>
  </div>
</div>
<?php endforeach; ?>

<?php // add at the end of the file after the table
  echo $this->paginationControl(
      // the paginator object
      $this->paginator,
      // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
      'sliding',
      // the partial to use to render the control
      array('partial/paginator.phtml', 'Blog'),
      // the route to link to when a user clicks a control link
      array(
          'route' => 'blog'
      )
  );
?>
