<?php
  $this->headTitle(strip_tags($post->post_title));
  if ($post->tags) {
    $this->headMeta()->appendName('keywords', $post->keywords);
  }
  $this->headMeta()->appendName('description', $post->post_metaDescription);
?>
<div class="blog-post">
  <h1><?php echo $post->post_title; ?></h1>
  <h3><?php echo $post->date; ?></h3>
  <?php if ($post->tags): ?>
    <div class="tag-list">Tags: <?php echo $post->tags; ?></div>
  <?php endif ?>
  <div class="blog-post-body">
    <?php echo $post->post_body; ?>
  </div>
</div>
