<?php
  $this->headTitle('Tags - '.$url_param_tag);
?>
<h1>Post that have been tagged with <?php echo $url_param_tag; ?> </h1>
<?php foreach ($tag_list as $post): ?>
<div class="blog-post">
  <h3><a href="<?php echo $this->url('blog/post', array('slug' => $post->page_url)); ?>"><?php echo $post->post_title; ?></a></h3>
  <h4><?php echo gmdate('n/j/Y - g:ia', $post->unix_time); ?></h4>
  <div class="blog-post-body">
    <?php echo $post->post_body; ?>
    <p class="read-more"><a href="<?php echo $this->url('blog/post', array('slug' => $post->page_url)); ?>">Read More &gt;</a></p>
  </div>
</div>
<?php endforeach; ?>
